version: "3.8"

services:
  db:
    image: mongo:latest
  split-node:
    image: split-node:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
  split-angular:
    image: split-angular:latest
    ports:
      - "80:80"
    depends_on:
      - split-node
